zookeeper:
    image: jplock/zookeeper:3.4.11
    container_name: zookeeper
    ports:
        - 2181:2181


kafka:
    image: ches/kafka:0.10.2.1
    container_name: kafka
    environment:
        - KAFKA_ADVERTISED_HOST_NAME=${KAFKA_ZHOST}
        - ZOOKEEPER_IP=${KAFKA_ZHOST}
    ports:
        - 7203:7203
        - 9092:9092


elassandra:
    image: erangaeb/elassandra:4.0
    container_name: elassandra
    environment:
        - CASSANDRA_BROADCAST_ADDRESS=${CASSANDRA_BROADCAST_ADDRESS}
        - CASSANDRA_SEEDS=${CASSANDRA_SEEDS}
    volumes:
        ['$CASSANDRA_DATA_DIR:/opt/cassandra/data']
    ports:
        - 7000:7000
        - 7001:7001
        - 7199:7199
        - 9042:9042
        - 9160:9160
        - 9200:9200
        - 9300:9300


3rest:
    image: erangaeb/3rest:0.1
    container_name: 3rest
    environment:
        - SENZIE_NAME=${REST_NAME}
        - KAFKA_KHOST=${KAFKA_KHOST}
        - KAFKA_KPORT=${KAFKA_KPORT}
        - KAFKA_ZHOST=${KAFKA_ZHOST}
        - KAFKA_ZPORT=${KAFKA_ZPORT}
    volumes:
        ['$REST_LOGS_DIR:/app/logs', '$REST_KEYS_DIR:/app/.keys']
    ports:
        - 7070:7070


3chain:
    image: erangaeb/3chain:0.1
    container_name: 3chain
    environment:
        - SENZIE_NAME=${CHAIN_NAME}
        - CASSANDRA_HOST=${CASSANDRA_HOST}
        - CASSANDRA_PORT=${CASSANDRA_PORT}
        - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
        - KAFKA_KHOST=${KAFKA_KHOST}
        - KAFKA_KPORT=${KAFKA_KPORT}
        - KAFKA_ZHOST=${KAFKA_ZHOST}
        - KAFKA_ZPORT=${KAFKA_ZPORT}
    volumes:
        ['$CHAIN_LOGS_DIR:/app/logs', '$CHAIN_KEYS_DIR:/app/.keys']


3ops:
    image: erangaeb/3ops:0.1
    container_name: 3ops
    environment:
        - SENZIE_NAME=${OPS_NAME}
        - CASSANDRA_HOST=${CASSANDRA_HOST}
        - CASSANDRA_PORT=${CASSANDRA_PORT}
        - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
        - KAFKA_KHOST=${KAFKA_KHOST}
        - KAFKA_KPORT=${KAFKA_KPORT}
        - KAFKA_ZHOST=${KAFKA_ZHOST}
        - KAFKA_ZPORT=${KAFKA_ZPORT}
    volumes:
        ['$OPS_LOGS_DIR:/app/logs', '$OPS_KEYS_DIR:/app/.keys']


3miner:
    image: erangaeb/3miner:0.1
    container_name: 3miner
    environment:
        - SENZIE_NAME=${MINER_NAME}
        - MINING_INTERVAL=${MINING_INTERVAL}
        - CASSANDRA_HOST=${CASSANDRA_HOST}
        - CASSANDRA_PORT=${CASSANDRA_PORT}
        - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
        - ELASTIC_CLUSTER=${ELASTIC_CLUSTER}
        - ELASTIC_HOST=${ELASTIC_HOST}
        - ELASTIC_PORT=${ELASTIC_PORT}
        - KAFKA_HOST=${KAFKA_HOST}
        - KAFKA_PORT=${KAFKA_PORT}
    volumes:
        ['$MINER_LOGS_DIR:/app/logs', '$MINER_KEYS_DIR:/app/.keys']


webz:
    image: maurakirinathan/webz:3.7
    container_name: webz
    environment:
        - CASSANDRA_HOST=${CASSANDRA_HOST}
        - CASSANDRA_PORT=${CASSANDRA_PORT}
        - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
    ports:
        - 81:8082
