zookeeper:
    image: jplock/zookeeper:3.4.11
    container_name: zookeeper
    ports:
        - 2181:2181


kafka:
    image: ches/kafka:0.10.2.1
    container_name: kafka
    environment:
        - KAFKA_ADVERTISED_HOST_NAME=${KAFKA_ZHOST}
        - ZOOKEEPER_IP=${KAFKA_ZHOST}
    ports:
        - 7203:7203
        - 9092:9092


elassandra:
    image: erangaeb/elassandra:3.0
    container_name: elassandra
    environment:
        - CASSANDRA_BROADCAST_ADDRESS=${CASSANDRA_BROADCAST_ADDRESS}
        - CASSANDRA_SEEDS=${CASSANDRA_SEEDS}
    volumes:
        ['$CASSANDRA_DATA_DIR:/opt/cassandra/data']
    ports:
        - 7000:7000
        - 7001:7001
        - 7199:7199
        - 9042:9042
        - 9160:9160
        - 9200:9200
        - 9300:9300


restz:
    image: erangaeb/3drestz:0.1
    container_name: restz
    environment:
        - SENZIE_NAME=${RESTZ_NAME}
        - KAFKA_KHOST=${KAFKA_KHOST}
        - KAFKA_KPORT=${KAFKA_KPORT}
        - KAFKA_ZHOST=${KAFKA_ZHOST}
        - KAFKA_ZPORT=${KAFKA_ZPORT}
    volumes:
        ['$RESTZ_LOGS_DIR:/app/logs', '$RESTZ_KEYS_DIR:/app/.keys']
    ports:
        - 7070:7070


chainz:
    image: erangaeb/3dchainz:0.1
    container_name: chainz
    environment:
        - SENZIE_NAME=${CHAINZ_NAME}
        - CASSANDRA_HOST=${CASSANDRA_HOST}
        - CASSANDRA_PORT=${CASSANDRA_PORT}
        - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
        - KAFKA_KHOST=${KAFKA_KHOST}
        - KAFKA_KPORT=${KAFKA_KPORT}
        - KAFKA_ZHOST=${KAFKA_ZHOST}
        - KAFKA_ZPORT=${KAFKA_ZPORT}
    volumes:
        ['$CHAINZ_LOGS_DIR:/app/logs', '$CHAINZ_KEYS_DIR:/app/.keys']


orderz:
    image: erangaeb/3dorderz:0.1
    container_name: orderz
    environment:
        - SENZIE_NAME=${ORDERZ_NAME}
        - CASSANDRA_HOST=${CASSANDRA_HOST}
        - CASSANDRA_PORT=${CASSANDRA_PORT}
        - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
        - KAFKA_KHOST=${KAFKA_KHOST}
        - KAFKA_KPORT=${KAFKA_KPORT}
        - KAFKA_ZHOST=${KAFKA_ZHOST}
        - KAFKA_ZPORT=${KAFKA_ZPORT}
    volumes:
        ['$ORDERZ_LOGS_DIR:/app/logs', '$ORDERZ_KEYS_DIR:/app/.keys']


minerz:
    image: erangaeb/3dminerz:0.1
    container_name: minerz
    environment:
        - SENZIE_NAME=${MINERZ_NAME}
        - CASSANDRA_HOST=${CASSANDRA_HOST}
        - CASSANDRA_PORT=${CASSANDRA_PORT}
        - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
        - ELASTIC_CLUSTER=${ELASTIC_CLUSTER}
        - ELASTIC_HOST=${ELASTIC_HOST}
        - ELASTIC_PORT=${ELASTIC_PORT}
        - KAFKA_HOST=${KAFKA_HOST}
        - KAFKA_PORT=${KAFKA_PORT}
    volumes:
        ['$MINERZ_LOGS_DIR:/app/logs', '$MINERZ_KEYS_DIR:/app/.keys']


webz:
    image: maurakirinathan/webz:3.7
    container_name: webz
    environment:
        - CASSANDRA_HOST=${CASSANDRA_HOST}
        - CASSANDRA_PORT=${CASSANDRA_PORT}
        - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
    ports:
        - 81:8082
