mongodb:
    image: erangaeb/senzmongodb:0.1
    container_name: senzmongodb
    volumes:
        ['$MONGO_DATA_DIR:/data/db']
    ports:
        - 27017:27017


zwitch:
    image: erangaeb/zwitch:1.0
    container_name: zwitch
    ports:
        - 7070:7070
    environment:
        - MONGO_HOST=${MONGO_HOST}
        - SWITCH_MODE=${SWITCH_MODE}
    volumes:
        ['$SWITCH_LOGS_DIR:/app/logs', '$SWITCH_KEYS_DIR:/app/.keys']
    links:
        - mongodb


cassandra:
    image: erangaeb/cassandra:0.6
    container_name: cassandra
    environment:
        - CASSANDRA_BROADCAST_ADDRESS=${CASSANDRA_BROADCAST_ADDRESS}
        - CASSANDRA_SEEDS=${CASSANDRA_SEEDS}
    volumes:
        ['$CASSANDRA_DATA_DIR:/opt/cassandra/data']
    ports:
        - 7000:7000
        - 9042:9042
        - 9060:9060


chainz:
    image: erangaeb/chainz:0.2
    container_name: chainz
    environment:
        - SENZIE_NAME=${CHAINZ_NAME}
        - CASSANDRA_HOST=${CASSANDRA_HOST}
        - CASSANDRA_PORT=${CASSANDRA_PORT}
        - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
        - SWITCH_HOST=${SWITCH_HOST}
        - SWITCH_PORT=${SWITCH_PORT}
    volumes:
        ['$CHAINZ_LOGS_DIR:/app/logs', '$CHAINZ_KEYS_DIR:/app/.keys']
    ports:
        - 5005:5005


cminer:
    image: erangaeb/cminer:0.5
    container_name: cminer
    environment:
        - SENZIE_NAME=${CMINER_NAME}
        - CASSANDRA_HOST=${CASSANDRA_HOST}
        - CASSANDRA_PORT=${CASSANDRA_PORT}
        - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
        - SWITCH_HOST=${SWITCH_HOST}
        - SWITCH_PORT=${SWITCH_PORT}
    volumes:
        ['$CMINER_LOGS_DIR:/app/logs', '$CMINER_KEYS_DIR:/app/.keys']


authz:
    image: erangaeb/authz:0.2
    container_name: authz
    environment:
        - SENZIE_NAME=${AUTHZ_NAME}
        - SENZIE_MODE=${AUTHZ_MODE}
        - CASSANDRA_HOST=${CASSANDRA_HOST}
        - CASSANDRA_PORT=${CASSANDRA_PORT}
        - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
        - SWITCH_HOST=${SWITCH_HOST}
        - SWITCH_PORT=${SWITCH_PORT}
    volumes:
        ['$AUTHZ_LOGS_DIR:/app/logs', '$AUTHZ_KEYS_DIR:/app/.keys']
    ports:
        - 5105:5005


web:
    image: hpcal1/blockchainweb:0.12
    container_name: web
    environment:
        - h1=${CASSANDRA_HOST}
        - APP_TYPE=${APP_TYPE}
    ports:
        - 80:3000
