mongodb:
    image: erangaeb/senzmongodb:0.1
    container_name: senzmongodb
    volumes:
        ['$MONGO_DATA_DIR:/data/db']
    ports:
        - 27017:27017


zwitch:
    image: erangaeb/zwitch:2.2
    container_name: zwitch
    ports:
        - 7171:7171
    environment:
        - MONGO_HOST=${MONGO_HOST}
        - SWITCH_MODE=${SWITCH_MODE}
        - CHAINZ_NAME=${CHAINZ_NAME}
        - CHAINZ_KEY=${CHAINZ_KEY}
        - PROMIZE_API=${PROMIZE_API}
        - UZER_API=${UZER_API}
    volumes:
        ['$SWITCH_LOGS_DIR:/app/logs', '$SWITCH_KEYS_DIR:/app/.keys', '$ZWITCH_CERTS_DIR:/app/.certs']
    links:
        - mongodb
        - chainz


cassandra:
    image: erangaeb/cassandra:0.6
    container_name: cassandra
    environment:
        - CASSANDRA_BROADCAST_ADDRESS=${CASSANDRA_BROADCAST_ADDRESS}
        - CASSANDRA_SEEDS=${CASSANDRA_SEEDS}
    volumes:
        ['$CASSANDRA_DATA_DIR:/opt/cassandra/data']
    ports:
        - 7000:7000
        - 9042:9042
        - 9060:9060


chainz:
    image: erangaeb/chainz:0.7
    container_name: chainz
    environment:
        - SENZIE_NAME=${CHAINZ_NAME}
        - CASSANDRA_HOST=${CASSANDRA_HOST}
        - CASSANDRA_PORT=${CASSANDRA_PORT}
        - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
        - SWITCH_HOST=${SWITCH_HOST}
        - SWITCH_PORT=${SWITCH_PORT}
        - TRANS_API=${TRANS_API}
        - TRANS_ACTION=${TRANS_ACTION}
        - TRANS_ACCOUNT=${TRANS_ACCOUNT}
    volumes:
        ['$CHAINZ_LOGS_DIR:/app/logs', '$CHAINZ_KEYS_DIR:/app/.keys']
    ports:
        - 5005:5005
        - 7070:7070


cminer:
    image: erangaeb/cminer:0.7
    container_name: cminer
    environment:
        - SENZIE_NAME=${CMINER_NAME}
        - CASSANDRA_HOST=${CASSANDRA_HOST}
        - CASSANDRA_PORT=${CASSANDRA_PORT}
        - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
        - SWITCH_HOST=${SWITCH_HOST}
        - SWITCH_PORT=${SWITCH_PORT}
    volumes:
        ['$CMINER_LOGS_DIR:/app/logs', '$CMINER_KEYS_DIR:/app/.keys']


authz:
    image: erangaeb/authz:0.3
    container_name: authz
    environment:
        - SENZIE_NAME=${AUTHZ_NAME}
        - SENZIE_MODE=${AUTHZ_MODE}
        - CASSANDRA_HOST=${CASSANDRA_HOST}
        - CASSANDRA_PORT=${CASSANDRA_PORT}
        - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
        - SWITCH_HOST=${SWITCH_HOST}
        - SWITCH_PORT=${SWITCH_PORT}
    volumes:
        ['$AUTHZ_LOGS_DIR:/app/logs', '$AUTHZ_KEYS_DIR:/app/.keys']
    ports:
        - 5105:5005


web:
    image: hpcal1/blockchainweb:0.12
    container_name: web
    environment:
        - h1=${CASSANDRA_HOST}
        - APP_TYPE=${APP_TYPE}
    ports:
        - 80:3000


webz:
    image: maurakirinathan/sampth_newui:v1
    container_name: webz
    environment:
        - CASSANDRA_HOST=${CASSANDRA_HOST}
        - CASSANDRA_PORT=${CASSANDRA_PORT}
        - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
    ports:
        - 8081:8081


nginx:
    image: erangaeb/senznginx:1.0
    container_name: nginx
    ports:
        - 80:80
        - 8443:8443
    volumes:
        ['$NGINX_CERTS_DIR:/etc/nginx/certs']
    links:
        - chainz
