mongodb:
    image: erangaeb/senzmongodb:0.1
    container_name: senzmongodb
    volumes:
        ['$MONGO_DATA_DIR:/data/db']
    ports:
        - 27017:27017


switch:
    image: erangaeb/senzswitch:0.59
    container_name: senzswitch
    ports:
        - 7070:7070
    environment:
        - MONGO_HOST=${MONGO_HOST}
        - SWITCH_MODE=${SWITCH_MODE}
    volumes:
        ['$SWITCH_LOGS_DIR:/app/logs', '$SWITCH_KEYS_DIR:/app/.keys']
    links:
        - mongodb


cassandra:
    image: erangaeb/cassandra:0.5
    container_name: cassandra
    environment:
        - CASSANDRA_BROADCAST_ADDRESS=${CASSANDRA_BROADCAST_ADDRESS}
        - CASSANDRA_SEEDS=${CASSANDRA_SEEDS}
    ports:
        - 7000:7000
        - 9042:9042
        - 9060:9060


cchain:
    image: erangaeb/cchain:0.8
    container_name: cchain
    environment:
        - SENZIE_NAME=${SENZIE_NAME}
        - CASSANDRA_HOST=${CASSANDRA_HOST}
        - CASSANDRA_PORT=${CASSANDRA_PORT}
        - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
        - SWITCH_HOST=${SWITCH_HOST}
        - SWITCH_PORT=${SWITCH_PORT}
    volumes:
        ['$CCHAIN_LOGS_DIR:/app/logs', '$CCHAIN_KEYS_DIR:/app/.keys']


web:
    image: hpcal1/blockchainweb:0.11
    container_name: web
    environment:
        - h1=${CASSANDRA_HOST}
        - APP_TYPE=${APP_TYPE}
    ports:
        - 80:3000
